Feat/48 54 application acceptance endpoint
lennygir/polito-se2-23-02-thesis pull request #34
Opened 2023-11-16 13:20 UTC by s317743

2023-11-20 21:16 UTC, lorber13 requested changes
Server ok. Must wait for the client

2023-11-21 07:49 UTC, valerianoCarlos approved these changes
ok

2023-11-21 23:21 UTC, valerianoCarlos approved these changes

2023-11-22 08:02 UTC, lorber13 approved these changes

2023-11-22 08:27 UTC, merged